status = [
	"test (ubuntu-stable)",
	"test (macos-stable)",
	"test (win-gnu-stable)",
	"test (win-msvc-stable)",
	"rustfmt",
	"clippy",
	"cargo_deny (advisories)",
	"cargo_deny (bans licenses sources)",
	"msrv"
]
